.if n.ad l
.nh

.TH daemon 1 "2018-10-10" "shellman 0.4.0" "User Commands"

.SH "NAME"
daemon \- Script allowing to start, pause, resume and stop daemons.

.SH "SYNOPSIS"
\fBdaemon\fR start

.SH "OPTIONS"
.IP "help, \fB\-h\fR, \fB\-\-help\fR" 4
Prints this help and exit.


.SH "EXAMPLES"
.IP "\fBStart the daemon called reencode.\fR" 4

  daemon start reencode
You can then pause, resume or stop it with
`daemon pause reencode`, `daemon resume reencode` or `daemon stop reencode`.
